# Generated by Django 4.2.1 on 2024-01-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_description',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='posted_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departments',
            name='read_more_link',
            field=models.CharField(default='some_default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doc_id',
            field=models.CharField(default='30', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='friday_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='monday_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='saturday_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='sunday_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='thursday_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='tuesday_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='wednesday_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
